name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
          - lint
          - audit
permissions:
  contents: write
jobs:
  check-and-build:
    if: inputs.job == 'build'
    uses: ./.github/workflows/rust-build.yaml
    secrets: inherit
    
  run-lint:
    if: inputs.job == 'lint'
    uses: ./.github/workflows/rust-lint.yaml
    
  run-audit:
    if: inputs.job == 'audit'
    uses: ./.github/workflows/rust-audit.yaml
