name: Rust Security Audit
on:
  workflow_call:
    inputs: {}
    secrets: {}
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-audit.yaml'
  workflow_dispatch:

jobs:
  audit:
    name: Rust Audit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run cargo audit
        run: cargo audit 